networks:
  accident-ml:
    name: accident-ml
    driver: bridge

services:
  accident-ml-db:
    image: postgres:17-alpine
    container_name: accident-ml-db
    networks:
      - accident-ml
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d accidents"]
      interval: 60s
      timeout: 10s
      retries: 3

  accident-ml-backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: ghcr.io/cpheat/road_accident_analysis-educational:develop
    container_name: accident-ml-backend
    depends_on:
      accident-ml-db:
        condition: service_healthy
    networks:
      - accident-ml
    ports:
      - "8000:8000"
    volumes:
      - backend_storage:/app/storage
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  accident-ml-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: cpheat/accident-ml-front:1.0.3
    container_name: accident-ml-front
    depends_on:
      accident-ml-backend:
        condition: service_healthy
    networks:
      - accident-ml
    ports:
      - "8501:8501"
    environment:
      API_URL: http://accident-ml-backend:8000
    volumes:
      - backend_storage:/app/storage
    restart: unless-stopped

volumes:
  backend_storage:
  postgres_data:
