name: Python application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: ""
      - name: Install dependencies
        run: |
          uv sync
      - name: Ruff check
        run: |
          uv run ruff check ./backend
      - name: Format check
        run: |
          uv run ruff format --check ./backend

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: ""
      - name: Install dependencies
        run: |
          uv sync
      - name: Type Check
        run: |
          uv run mypy ./backend/

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: ""
      - name: Install dependencies
        run: |
          uv sync
      - name: security check
        run: |
          uv run bandit -r ./backend/
      - name: Safety check
        run: |
          uv run safety check

  # tests:
  #   runs-on: ubuntu-latest
  #   container: node:20-bookworm-slim
  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #       - 5432:5432

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up UV
  #       uses: astral-sh/setup-uv@v7
  #       with:
  #         enable-cache: true
  #         cache-dependency-glob: "uv.lock"
  #         version: ""
  #     - name: Install dependencies
  #       run: |
  #         uv sync
  #     - name: Run tests
  #       run: |
  #         uv run pytest --cov=app --cov-report=term --cov-report=xml
  #     # - name: Upload coverafe to codecov


    